### ISSUE TITLE
Main module not updating to v2.8.2

### ISSUE THREAD

**Issue by CreamDevelopment** [wl-online-payments-direct/plugin-magento-graph-ql#7]
When trying to install v2.8.2 of worldine/module-magento-payment, I get the following error:
```
  Problem 1
    - Root composer.json requires worldline/module-magento-payment 2.8.2 -> satisfiable by worldline/module-magento-payment[2.8.2].
    - worldline/module-magento-payment 2.8.2 requires worldline/module-magento-payment-graph-ql 1.1.2 -> found worldline/module-magento-payment-graph-ql[1.0.0, 1.1.0, 1.1.1] but it does not match the constraint.
```

Magento: v2.4.6 CE
PHP: v8.1

Could you please check this module so we can update?

**Comment by WorldlineShoppingCarts** [comment]
Hi @CreamDevelopment,

We are looking into this issue and will keep you informed as soon as we have any relevant updates.

**Comment by WorldlineShoppingCarts** [comment]
Hi @CreamDevelopment,
We are unable to see from our end what could be causing this issue. The composer file dependencies are correct for each package and should automatically install graph-QL 1.1.2
Our developers suggest that you try to update the graph-QL module with composer using “update worldline/module-magento-payment-graph-ql”
Could you let us know if this helps resolve the issue?

**Comment by CreamDevelopment** [comment]
Hi @WorldlineShoppingCarts,

Unfortunately, this did not work. Even when I completely removed all worldline modules and tried `composer require worldline/module-magento-payment-graph-ql` (with or w/o version number), it didn't work. In that las try, I got the error '  Could not find package worldline/module-magento-payment-graph-ql in a version matching "1.1.2" and a stability matching "dev".'

**Comment by CreamDevelopment** [comment]
Hi @WorldlineShoppingCarts,

After my previous comment, I checked the composer files again. The module source was set as Magento Marketplace, so that wasn't right. I suspect we've had this problem before, because we have all other modules mentioned in composer.json in the following manner:
```
    "repositories": {
        "worldline/module-magento-payment-creditcard": {
            "type": "git",
            "url": "https://github.com/wl-online-payments-direct/plugin-magento-creditcard.git"
        },
        "worldline/module-magento-payment-redirect-payment": {
            "type": "git",
            "url": "https://github.com/wl-online-payments-direct/plugin-magento-redirect-payments.git"
        },
        "worldline/module-magento-payment-hostedcheckout": {
            "type": "git",
            "url": "https://github.com/wl-online-payments-direct/plugin-magento-hostedcheckout.git"
        },
        "worldline/module-magento-payment-core": {
            "type": "git",
            "url": "https://github.com/wl-online-payments-direct/plugin-magento-core.git"
        },
        "worldline/module-magento-payment": {
            "type": "git",
            "url": "https://github.com/wl-online-payments-direct/plugin-magento.git"
        },
        "worldline/module-magento-payment-graph-ql": {
            "type": "git",
            "url": "https://github.com/wl-online-payments-direct/plugin-magento-graph-ql.git"
        },
        "magento": {
            "type": "composer",
            "url": "https://repo.magento.com/",
            "canonical": false
        },
...
```
As you can see, I added the graph-ql module to this list, and then it worked.

**Comment by WorldlineShoppingCarts** [comment]
Hi @CreamDevelopment,
We are glad to hear the issue is resolved.
Going forth, to ensure you have the latest release at the earliest possible, we would recommend that you pull from github. The reason being that new releases will be pushed to gitbuh first, then published to the Marketplace, but due to the need for human action and the waiting period for validation of the plugin, it can take a while before the same release is available on the Marketplace.
If you encounter any other issue with our plugin, we are here to help.
Have a good day.
